pipeline:
  build:
    image: python:3.6
    environment:
      - DJANGO_SETTINGS_MODULE=app.settings.prod
      - DATABASE_USER=${PARTISK_DB_USER}
      - DATABASE_PASSWORD=${PARTISK_DB_PASSWORD}
      - DATABASE_HOST=db
      - SECRET_KEY=${DJANGO_SECRET}
      - ADMIN_ENABLED=False
      - COMPRESS=False
      - DEBUG=True
    commands:
      - pip install --trusted-host pypi.python.org -r python_requirements.txt
    when:
      branch: [master]
      event: [push, pull_request]

  publish:
    environment:
      - DOCKER_USERNAME=${DOCKER_USERNAME}
      - DOCKER_PASSWORD=${DOCKER_PASSWORD}
    secrets: [docker_username, docker_password]
    image: plugins/docker:17.12
    #registry: ${REGISTRY_URL}
    #username: ${REGISTRY_USERNAME}
    #password: ${REGISTRY_PASSWORD}
    #email: ${REGISTRY_EMAIL}
    #repo: ci.presight.se:5000/partisk/web
    #tag: ${REGISTRY_URL}/partisk/web
    #file: Dockerfile
    insecure: false
    environment:
      - DOCKER_LAUNCH_DEBUG=true
    debug: true
    #image: docker
    #secrets: [docker_username,docker_password]
    #commands:
        #- docker login $$A d $A b $B c $BB --username=$DOCKER_USERNAME --password=$$DOCKER_PASSWORD $${REGISTRY_URL}a${REGISTRY_URL}
    #    - docker build -t ${REGISTRY_URL}/partisk/web:master .
    #    - docker push ${REGISTRY_URL}/partisk/web:master
    #volumes:
    #    - /var/run/docker.sock:/var/run/docker.sock
    #when:
    #    branch: master
    #    status: success

