pipeline:
  build:
    image: python:3.6
    environment:
      - DJANGO_SETTINGS_MODULE=app.settings.prod
      - DATABASE_USER=${PARTISK_DB_USER}
      - DATABASE_PASSWORD=${PARTISK_DB_PASSWORD}
      - DATABASE_HOST=db
      - SECRET_KEY=${DJANGO_SECRET}
      - ADMIN_ENABLED=False
      - COMPRESS=False
      - DEBUG=True
    commands:
      - pip install --trusted-host pypi.python.org -r python_requirements.txt
    when:
      branch: [master]
      event: [push, pull_request]

  publish:
    image: plugins/docker
    registry: ${REGISTRY_URL}
    username: ${REGISTRY_USERNAME}
    password: ${REGISTRY_PASSWORD}
    email: ${REGISTRY_EMAIL}
    repo: partisk/web
    tag: ${DRONE_REPO_BRANCH}
    file: Dockerfile
    insecure: false
    environment:
      - DOCKER_LAUNCH_DEBUG=true
    debug: true
