pipeline:
  #build:
  #  image: python:3.6
  #  environment:
  #    - DJANGO_SETTINGS_MODULE=app.settings.prod
  #    - DATABASE_USER=${PARTISK_DB_USER}
  #    - DATABASE_PASSWORD=${PARTISK_DB_PASSWORD}
  #    - DATABASE_HOST=db
  #    - SECRET_KEY=${DJANGO_SECRET}
  #    - ADMIN_ENABLED=False
  #    - COMPRESS=False
  #    - DEBUG=True
  #  commands:
  #    - pip install --trusted-host pypi.python.org -r python_requirements.txt
  #  when:
  #    branch: [master]
  #    event: [push, pull_request]

  publish:
    secrets: [docker_username, docker_password, registry, repo]
    image: plugins/docker:17.10
    registry: ci.presight.se:5000
    repo: ci.presight.se:5000/partisk/web
    tag: ${DRONE_BUILD_NUMBER}
    file: Dockerfile
    insecure: false
    #environment:
    #  - DOCKER_LAUNCH_DEBUG=true
    #debug: true

  notify:
      image: plugins/slack
      channel: utveckling
      secrets: [ slack_webhook ]
      template: >
           {{#success build.status}}
             build {{build.link}} succeeded. Good job.
           {{else}}
             build {{build.link}} failed. Fix me please.
           {{/success}}
      when:
        status: [ success, failure ]
           
