pipeline:
  build:
    image: python:3.6
    environment:
      - DJANGO_SETTINGS_MODULE=app.settings.prod
      - DATABASE_USER=$PARTISK_DB_USER
      - DATABASE_PASSWORD=$PARTISK_DB_PASSWORD
      - DATABASE_HOST=db
      - SECRET_KEY=$DJANGO_SECRET
      - ADMIN_ENABLED=False
      - COMPRESS=False
      - DEBUG=True
    commands:
      - pip install --trusted-host pypi.python.org -r python_requirements.txt
    when:
      branch: [ master ]
      event: [push, pull_request]

