pipeline:
  #build:
  #  image: python:3.6
  #  environment:
  #    - DJANGO_SETTINGS_MODULE=app.settings.prod
  #    - DATABASE_USER=${PARTISK_DB_USER}
  #    - DATABASE_PASSWORD=${PARTISK_DB_PASSWORD}
  #    - DATABASE_HOST=db
  #    - SECRET_KEY=${DJANGO_SECRET}
  #    - ADMIN_ENABLED=False
  #    - COMPRESS=False
  #    - DEBUG=True
  #  commands:
  #    - pip install --trusted-host pypi.python.org -r python_requirements.txt
  #  when:
  #    branch: [master]
  #    event: [push, pull_request]

  publish:
    secrets: [docker_username, docker_password]
    image: plugins/docker:17.10
    registry: registry:5000
    repo: registry:5000/partisk/web/a$REGISTRY_URLb$$REGISTRY_URLc${REGISTRY_URL}d$${REGISTRY_URL}
    #tag: ${REGISTRY_URL}/partisk/web
    file: Dockerfile
    insecure: false
    environment:
      - DOCKER_LAUNCH_DEBUG=true
    debug: true
