pipeline:
  test:
    image: python:3.6
    environment:
      - DJANGO_SETTINGS_MODULE=app.settings.prod
      - DATABASE_USER=root
      - DATABASE_PASSWORD=partisktest
      - DATABASE_HOST=database
      - SECRET_KEY=verysecret
      - ADMIN_ENABLED=False
      - COMPRESS=False
      - DEBUG=True
    commands:
      - pip install --trusted-host pypi.python.org -r python_requirements.txt
      - python manage.py test
    when:
      branch: [master, develop]
      event: [push, pull_request]

  publish:
    secrets: [docker_username, docker_password]
    image: plugins/docker:17.10
    registry: ci.presight.se:5000
    repo: ci.presight.se:5000/partisk/web
    tag: ${DRONE_BUILD_NUMBER}
    file: Dockerfile
    insecure: false

  notify:
      image: plugins/slack
      channel: utveckling
      secrets: [ slack_webhook ]
      template: >
           {{#success build.status}}
             build {{build.link}} succeeded. Good job.
           {{else}}
             build {{build.link}} failed. Fix me please.
           {{/success}}
      when:
        status: [ success, failure ]

services:
  database:
    image: mysql:5.7.22
    environment:
      - MYSQL_ROOT_PASSWORD=partisktest
      - MYSQL_DATABASE=partisk
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
