# Generated by Django 2.0.2 on 2018-03-06 22:39

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('source', models.TextField()),
                ('date', models.DateTimeField()),
                ('deleted', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('approved', models.BooleanField(default=False)),
                ('created_by', models.IntegerField(default=None, null=True)),
            ],
            options={
                'db_table': 'answers',
            },
        ),
        migrations.CreateModel(
            name='AnswerType',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('answer', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'answer_type',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('text', models.TextField()),
                ('ip', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('referer', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'feedback',
            },
        ),
        migrations.CreateModel(
            name='Kommun',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40, null=True)),
                ('lan', models.CharField(max_length=2)),
            ],
            options={
                'db_table': 'kommuner',
            },
        ),
        migrations.CreateModel(
            name='Lan',
            fields=[
                ('id', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40, null=True)),
            ],
            options={
                'db_table': 'lan',
            },
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.AutoField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('website', models.CharField(max_length=100)),
                ('twitter', models.CharField(default=None, max_length=100, null=True)),
                ('color', models.TextField()),
                ('deleted', models.IntegerField(default=False)),
                ('last_result_parliment', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('last_result_eu', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('updated_by', models.IntegerField(blank=True, default=None, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('short_name', models.CharField(blank=True, max_length=5, null=True)),
                ('created_by', models.IntegerField(default=None, null=True)),
            ],
            options={
                'db_table': 'parties',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('deleted', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.TextField(blank=True, null=True)),
                ('approved', models.BooleanField(default=False)),
                ('approved_date', models.DateTimeField(auto_now_add=True)),
                ('done', models.BooleanField(default=False)),
                ('version', models.IntegerField(blank=True, null=True)),
                ('created_by', models.IntegerField(default=None, null=True)),
            ],
            options={
                'db_table': 'questions',
            },
        ),
        migrations.CreateModel(
            name='QuestionQuizzes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='partisk.Question')),
            ],
            options={
                'db_table': 'question_quizzes',
            },
        ),
        migrations.CreateModel(
            name='QuestionTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='partisk.Question')),
            ],
            options={
                'db_table': 'question_tags',
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('approved', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('approved_date', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.IntegerField(default=None, null=True)),
            ],
            options={
                'db_table': 'quizzes',
            },
        ),
        migrations.CreateModel(
            name='QuizAnswer',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('importance', models.IntegerField()),
                ('answer_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='partisk.AnswerType')),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='partisk.Question')),
            ],
            options={
                'db_table': 'quiz_answers',
            },
        ),
        migrations.CreateModel(
            name='QuizResults',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('data', models.TextField()),
                ('created', models.DateField(default=datetime.date.today)),
                ('version', models.IntegerField()),
                ('quiz', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='partisk.Quiz')),
            ],
            options={
                'db_table': 'quiz_results',
            },
        ),
        migrations.CreateModel(
            name='QuizResultsInfo',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('date', models.DateField(default=datetime.date.today)),
                ('country', models.CharField(max_length=40)),
                ('city', models.CharField(max_length=40)),
                ('postal_code', models.CharField(max_length=40)),
                ('coordinates', models.CharField(max_length=40)),
                ('accuracy', models.IntegerField()),
                ('subdivision', models.CharField(max_length=40)),
                ('kommun', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='partisk.Kommun')),
                ('lan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='partisk.Lan')),
                ('quiz', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='partisk.Quiz')),
            ],
            options={
                'db_table': 'quiz_results_info',
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(null=True)),
                ('content', models.TextField(null=True)),
                ('last_updated', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'source',
            },
        ),
        migrations.CreateModel(
            name='SourceType',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'source_type',
            },
        ),
        migrations.CreateModel(
            name='Stuff',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.TextField(null=True)),
                ('title', models.CharField(max_length=400)),
                ('content', models.TextField(null=True)),
                ('content_hash', models.CharField(blank=True, max_length=32, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('handled', models.BooleanField(default=False)),
                ('parties', models.ManyToManyField(blank=True, to='partisk.Party')),
                ('questions', models.ManyToManyField(blank=True, to='partisk.Question')),
                ('source_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='partisk.SourceType')),
            ],
            options={
                'db_table': 'stuff',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(default=None, null=True)),
                ('is_category', models.NullBooleanField()),
                ('created_by', models.IntegerField(default=None, null=True)),
                ('updated_by', models.IntegerField(default=None, null=True)),
            ],
            options={
                'db_table': 'tags',
            },
        ),
        migrations.AddField(
            model_name='stuff',
            name='tags',
            field=models.ManyToManyField(blank=True, to='partisk.Tag'),
        ),
        migrations.AddField(
            model_name='source',
            name='source_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='partisk.SourceType'),
        ),
        migrations.AddField(
            model_name='quizanswer',
            name='quiz_results_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='partisk.QuizResultsInfo'),
        ),
        migrations.AddField(
            model_name='questiontags',
            name='tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='partisk.Tag'),
        ),
        migrations.AddField(
            model_name='questionquizzes',
            name='quiz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='partisk.Quiz'),
        ),
        migrations.AddField(
            model_name='question',
            name='tags',
            field=models.ManyToManyField(blank=True, through='partisk.QuestionTags', to='partisk.Tag'),
        ),
        migrations.AddField(
            model_name='answer',
            name='answer_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='partisk.AnswerType'),
        ),
        migrations.AddField(
            model_name='answer',
            name='party',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='partisk.Party'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='partisk.Question'),
        ),
    ]
