# Generated by Django 2.0.2 on 2018-03-06 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partisk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stuff',
            name='answers',
            field=models.ManyToManyField(blank=True, to='partisk.Answer'),
        ),
    ]
