# Generated by Django 2.0.2 on 2018-03-09 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partisk', '0002_stuff_answers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['title']},
        ),
        migrations.RemoveField(
            model_name='stuff',
            name='answers',
        ),
        migrations.RemoveField(
            model_name='stuff',
            name='questions',
        ),
        migrations.AddField(
            model_name='answer',
            name='stuff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='partisk.Stuff'),
        ),
    ]
