# Generated by Django 2.0.2 on 2018-04-12 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partisk', '0004_auto_20180310_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='stuff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='partisk.Stuff'),
        ),
    ]
