# Generated by Django 2.0.2 on 2018-04-29 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partisk', '0005_auto_20180412_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='outdated',
            field=models.BooleanField(default=False),
        ),
    ]
