# Generated by Django 2.0.5 on 2018-05-12 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partisk', '0006_answer_outdated'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='questions',
            field=models.ManyToManyField(through='partisk.QuestionQuizzes', to='partisk.Question'),
        ),
        migrations.AddField(
            model_name='tag',
            name='questions',
            field=models.ManyToManyField(through='partisk.QuestionTags', to='partisk.Question'),
        ),
    ]
