# Generated by Django 2.0.5 on 2018-05-14 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partisk', '0007_auto_20180512_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='created_by',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
